### ISSUE TITLE
revert in-repo config changes?

### ISSUE THREAD

**Issue by CASEYGUNGEON** [CASEYGUNGEON/phoenix-ss13#37]
### Type of Request

Change

### About the Request

i did it before i knew how to use them better and now they should probably be reverted. maybe?

### Why should this Idea be considered

it's silly

**Comment by whataboutism-alos** [comment]
If all you did was change the old default config in the repo to reflect our community I think that's a good thing tbh

**Comment by CASEYGUNGEON** [comment]
i need to go back and look at exactly what's changed but yeah a decent chunk of it is probably fine as is rn
